#!/bin/sh

# rsync home backup
rsync -avz --ignore-errors -e ssh --delete --progress \
--exclude Downloads \
--exclude Music \
--exclude Videos \
--exclude Public \
--exclude Templates \
--exclude .nix-channels \
--exclude .nix-defexpr \
--exclude .nix-profile \
--exclude .cache \
--exclude .dbus \
--exclude .mozilla \
/home/djwilcox macmini:rsync/nixos
