#!/bin/sh

# backup home to usb
rsync -aAXvz --ignore-errors --delete --progress \
--exclude Downloads \
--exclude Music \
--exclude Videos \
--exclude .nix-channels \
--exclude .nix-defexpr \
--exclude .nix-profile \
--exclude .cache \
--exclude .dbus \
--exclude .mozilla \
/home/djwilcox /var/run/media/djwilcox/backup
