#!/bin/sh

# backup home to usb
rsync -aAXvz --ignore-errors --delete --progress \
--exclude bin \
--exclude Downloads \
--exclude Music \
--exclude Videos \
--exclude .nix-channels \
--exclude .nix-defexpr \
--exclude .nix-profile \
--exclude .cache \
--exclude .kodi \
--exclude .local \
--exclude .mozilla \
--exclude .nv \
--exclude .nvidia-settings-rc \
--exclude .pki \
--exclude .ssh \
/home/djwilcox /var/run/media/djwilcox/backup
