#!/bin/sh

# openvpn split route with namespace
#===================================

# openvpn up script
up() {
    # create network namespace
    ip netns add vpn || true

    # create vpn namespace directory
    mkdir -p /var/run/netns/vpn

    # create resolv.conf with 
    echo 'nameserver 8.8.8.8' > /var/run/netns/vpn/resolv.conf 

    # unmount
    umount /var/run/netns/vpn
    mount --bind /proc/self/ns/net /var/run/netns/vpn

    # bring up loop device
    ip netns exec vpn ip link set dev lo up

    # move VPN tunnel to netns
    ip link set dev "$1" up netns vpn mtu "$2"

    # configure tunnel in netns
    ip netns exec vpn ip addr add dev "$1" \
            "$4/${ifconfig_netmask:-30}" \
            ${ifconfig_broadcast:+broadcast "$ifconfig_broadcast"}
    if [ -n "$ifconfig_ipv6_local" ]; then
            ip netns exec vpn ip addr add dev "$1" \
                    "$ifconfig_ipv6_local"/112
    fi

    # set route in netns
    ip netns exec vpn ip route add default via "$route_vpn_gateway"

}

# openvpn down script
down() {
    # remove namespace and delete resolv.conf
    unmount /var/run/netns/vpn
    rm -rf /etc/netns/vpn
    ip netns delete vpn

    true
}

"$script_type" "$@"