#!/bin/sh

# transmission-pwgen generate passwords for transmission 

# Define the password length.
PASSWORD_LENGTH=64

# Generate a random password (alphanumeric).
PASS=$(tr -dc '[:alnum:]' < /dev/urandom | fold -w ${PASSWORD_LENGTH} | head -n1)

# Generate a random salt (alphanumeric + two special characters).
# Source: https://github.com/transmission/transmission/blob/master/libtransmission/crypto-utils.c#L132-L136
SALT=$(tr -dc '[:alnum:]./' < /dev/urandom | fold -w 8 | head -n1)

# Combine password + salt and use sha1sum to create the hash.
HASH=$(echo "${PASS}${SALT}" | sha1sum | awk '{print $1}')

# Print the plain text password.
echo "plain_text_password = ${PASS}"

# Print the rpc-password string: hash + salt prepended with a curly bracket.
# Source: https://github.com/transmission/transmission/blob/master/libtransmission/crypto-utils.c#L153
echo "rpc_password_string = {${HASH}${SALT}"
