#!/bin/sh

# trdvpn - run transmission in a seperate network namespace

# ip netns exec vpn namespace, doas switch to transmission user and start the daemon
doas ip netns exec vpn doas -u transmission transmission-daemon -g /var/lib/transmission/.config/transmission-daemon
