#!/bin/sh

#===============================================================================
# check if we are running Gnome and then exit
#===============================================================================

if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ]; then
    echo "$(date): Running in Gnome session. Exiting status-bar script." >> "/tmp/status-bar-debug.log"
    exit 0
fi

#===============================================================================
# check the number of arguments passed to the script
#===============================================================================

[ $# -gt 0 ] || exit 0


#===============================================================================
# wallpaper
#===============================================================================

# image for wallpaper
image="${HOME}/Pictures/wallpaper/akira-wallpaper.png"

# run wbg and set the wallpaper
wbg "${image}"
